namespace foo

class Bar

    sub error1()
        a = Rnd(10)
        if a > 0
            b = 0
        end if
        print "b"; b 'error
    end sub

    sub error2()
        m.ok1(sub()
            a = Rnd(10)
            if a > 0
                b = 0
            end if
            print "b"; b 'error
        end sub)
    end sub

    sub ok1(_)
        a = Rnd(10)
        if a > 0
            b = 0
        else
            b = 1
        end if
        print "b"; b
    end sub

end class

end namespace
